// Generated by package-icudata.py
#include <stdint.h>
#pragma clang diagnostic ignored "-Wc23-extensions"
#ifdef __cplusplus
extern "C" {
#endif
__attribute__((aligned(16))) const uint8_t icudt74_dat[] = {
#embed "icudt74l.dat"
};
#ifdef __cplusplus
}
#endif
