#!/usr/bin/env python3
import json
import subprocess
from pathlib import Path
import shutil

ICU_VERSIONS_FILE = Path(__file__).parent.parent / "icu-versions.json"
PACKAGE_SCRIPT = Path(__file__).parent / "package-icudata.py"
OUTPUT_BASE = Path(__file__).parent.parent / "Sources"

def build_with_filter(filter_json: Path, filter_name: str, versions: dict, args):
    print(f"Building with filter {filter_json}")
    icu_versions = set(versions["swift-icu-versions"].values())
    build_dir = Path(__file__).parent.parent / ".build" / "icu"

    for icu_version in icu_versions:
        out_dir = OUTPUT_BASE / f"icudata/{icu_version}"
        out_dir.mkdir(parents=True, exist_ok=True)
        out_c = out_dir / filter_name / "icudata.c"
        print(f"Building ICU data {icu_version} -> {out_c}")
        if out_c.exists() and not args.clean:
            print(f"Skipping {out_c} because it already exists")
            continue

        per_filter_build_dir = build_dir / filter_name
        if args.clean and per_filter_build_dir.exists():
            print(f"Cleaning build directory {per_filter_build_dir}")
            for item in per_filter_build_dir.iterdir():
                if item.is_file():
                    item.unlink()
                else:
                    shutil.rmtree(item)

        args = [
            "python3", str(PACKAGE_SCRIPT),
            "--icu-version", icu_version,
            "--filter-json", str(filter_json),
            "--output", str(out_c),
            "--build-dir", str(per_filter_build_dir)
        ]
        print(f"Running {' '.join(args)}")
        subprocess.run(args, check=True)

    for swift_version in versions["swift-icu-versions"]:
        icu_version = versions["swift-icu-versions"][swift_version]
        out_dir = OUTPUT_BASE / f"ICUDataSlim_{swift_version.replace('.', '_')}" / filter_name
        out_dir.mkdir(parents=True, exist_ok=True)
        out_c = out_dir / "icudata.c"
        print(f"Generating C source file for Swift {swift_version} -> {out_c}")
        with open(out_c, "w") as f:
            f.write(f"// Generated by build-all.py\n")
            f.write(f"#include \"../../icudata/{icu_version}/{filter_name}/icudata.c\"\n")

        out_empty_h = out_dir / "include" / "empty.h"
        out_empty_h.parent.mkdir(parents=True, exist_ok=True)
        out_empty_h.touch()


def parse_args():
    import argparse
    parser = argparse.ArgumentParser(description="Build ICU data for all filters and versions.")
    parser.add_argument("--clean", action="store_true", help="Clean build directories before building")
    return parser.parse_args()


def main():
    args = parse_args()
    with open(ICU_VERSIONS_FILE) as f:
        versions = json.load(f)

    filters_dir = Path(__file__).parent / "filters"
    for filter_file in filters_dir.glob("*.json"):
        build_with_filter(filter_file, filter_file.stem, versions, args)


if __name__ == "__main__":
    main()
